fix(tests): disuse setuptools build backend in favor of hatchling
When installed in editable mode, setuptools installs a .pkg-info in site-packages,
but also leaves an .egg-info in the project directory.
This results in importlib.metadata.distributions() listing the distribution twice,
which can confuse Lektor in some circumstances causing it to fail with:

   RuntimeError: Plugin "markdown-header-anchors" is already registered

So, here, we use hatchling which does not leave an .egg-info lying around

Refs: python/importlib_metadata#481, pypa/setuptools#3649